#端口号
server:
  port: 9920
#服务名和数据源(连接池)
spring:
  application:
    name: backendservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cz_health?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
#注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9900/eureka