#端口号
server:
  port: 9900
#服务名
spring:
  application:
    name: healtheureka
#注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9900/eureka
    register-with-eureka: false #关闭注册自己
    fetch-registry: false       #关闭拉取列表